### PR TITLE
refactor: extract utility logic for tests

### PR DESCRIPTION
**Pull request by pihme**
## Description

We already talked about refactoring the logic we use in the tests. I started doing this for #2 and the realized, I would like to have it in main earlier, and extracted this smaller PR.

The content is a bit narrow and motivated by what I am going to need in #2.

I tried modifying the existing test, but this got messy quite quickly. 

So, since there really is no perfect time, this PR serves as a start for having this class in the code base.

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually

Documentation:
* [ ] The documentation is updated

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
⭐ I like this change! It is now not used in any of the tests, is that on purpose or did you forget to commit something?

Either way this code looks good

**Comment by pihme** [comment]
> star I like this change! It is now not used in any of the tests, is that on purpose or did you forget to commit something?

It will be used in #2. I wanted to keep the change set small.

**Comment by pihme** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
@pihme I don't think we have bors in this repo yet

**Comment by pihme** [comment]
> @pihme I don't think we have bors in this repo yet

Old habits :-)

**Pull request merged**
